# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: Join us as the 2017 National Extension Technology Community Annual Conference convenes in Savannah on June 12-15. Examine technological trends, share ideas and network with your peers while immersed in the natural beauty, charm, architecture and history of the South. Georgia’s First City will captivate, intrigue, and surprise you with her gracious hospitality and subtle eccentricities.
baseurl: "" # the subpath of your site, e.g. /blog FOR SOME REASON, TO TEST LOCALLY, MAKE BASEURL "" AND TO TEST ON GH-PAGES, MAKE IT "/NETC"
url: "http://www.netc2017.org" # the base hostname & protocol for your site
root: '/'

# Build settings
markdown: kramdown
theme: minima

sass:
    sass_dir: _sass
    style: compressed

exclude: [node_modules, Gruntfile.js, package.json]
